/*
 * visualizer-core.js
 * Shared butterchurn controller used by both obs.html and fullscreen.html.
 *
 * Loaded as a classic script (NOT an ES module) so it works from file://
 * without CORS issues. Exposes a single global: window.BCViz.
 *
 * Requires butterchurn + butterchurn-presets to be loaded first.
 *
 * Usage:
 *   const viz = BCViz.create(canvasEl, {
 *     onToast:  (msg)        => {},   // brief status messages
 *     onPreset: (index,name) => {},   // fires whenever the preset changes
 *     cycleSecs: 20,
 *     cycleOn:  true
 *   });
 *   await viz.start();                // needs a user gesture first
 */
(function (global) {
  'use strict';

  function getLib(name) {
    const m = global[name];
    return m && (m.default || m);
  }

  function create(canvas, opts) {
    opts = opts || {};
    const Butterchurn = getLib('butterchurn');
    const onToast  = opts.onToast  || function () {};
    const onPreset = opts.onPreset || function () {};
    const defaultBlend = opts.blend != null ? opts.blend : 2.7;

    let audioCtx, visualizer, micStream, sourceNode;
    let presets = {}, keys = [], idx = 0;
    let excluded = new Set(); // preset keys removed from rotation for this session
    let failed = new Set();   // preset keys that failed to load/apply (auto-skipped)
    let cycleOn = opts.cycleOn !== false;
    let shuffleOn = opts.shuffle === true;
    let cycleSecs = opts.cycleSecs || 20;
    let cycleTimer = null;
    let inputDevices = [], deviceIdx = 0;
    let started = false, starting = false;

    // Merge every available preset pack. Packs are optional (a missing
    // script just means fewer presets); on name collisions the earlier
    // pack wins, so add-on packs never override or duplicate base presets.
    ['butterchurnPresets', 'butterchurnPresetsExtra',
     'butterchurnPresetsExtra2', 'butterchurnPresetsMD1'].forEach(function (name) {
      const pack = getLib(name);
      if (!pack || !pack.getPresets) return;
      const packPresets = pack.getPresets();
      Object.keys(packPresets).forEach(function (k) {
        if (!(k in presets)) presets[k] = packPresets[k];
      });
    });
    // Fold in the lazily loaded extra-preset index (generated by
    // tools/fetch-extra-presets.py into presets-extra/). Only names appear
    // here; the preset data itself lives in chunk files that are injected
    // as <script> tags on demand — fetch() of local JSON doesn't work from
    // file://, so this keeps the huge collection portable. The index is
    // optional: if presets-extra/index.js is absent the app behaves exactly
    // as before. On name collisions the vendored packs win, same policy as
    // between packs above.
    const extraChunkOf = {};  // preset name -> chunk id (not yet resident)
    const extraIndex = global.BCExtraPresetIndex;
    if (extraIndex && extraIndex.chunks) {
      extraIndex.chunks.forEach(function (names, cid) {
        names.forEach(function (n) {
          if (!(n in presets) && !(n in extraChunkOf)) extraChunkOf[n] = cid;
        });
      });
    }
    keys = Object.keys(presets).concat(Object.keys(extraChunkOf)).sort();

    // --- Lazy chunk loading -------------------------------------------------
    // A chunk file calls window.__bcPresetChunk(id, {name: preset, ...}) when
    // it executes. Loaded chunks are kept in a small LRU cache so a long
    // session doesn't accumulate all ~60MB of preset data.
    const chunkCacheMax = opts.chunkCacheMax || 16; // ~10MB of parsed presets
    const chunkState = {};   // cid -> 'loading' | 'loaded' | 'failed'
    const chunkWaiters = {}; // cid -> [resolve(boolean), ...]
    const chunkScripts = {}; // cid -> injected <script> element
    const chunkOwned = {};   // cid -> names this chunk registered
    let chunkLRU = [];       // loaded cids, least recently used first

    function settleChunk(cid, ok) {
      const waiters = chunkWaiters[cid] || [];
      delete chunkWaiters[cid];
      waiters.forEach(function (resolve) { resolve(ok); });
    }

    function touchChunk(cid) {
      chunkLRU = chunkLRU.filter(function (c) { return c !== cid; });
      chunkLRU.push(cid);
    }

    // Drops least-recently-used chunks over the cache cap. Never evicts the
    // chunk backing the currently playing preset.
    function evictChunks() {
      const currentCid = extraChunkOf[keys[idx]];
      while (chunkLRU.length > chunkCacheMax) {
        let vi = -1;
        for (let n = 0; n < chunkLRU.length; n++) {
          if (chunkLRU[n] !== currentCid) { vi = n; break; }
        }
        if (vi < 0) return;
        const cid = chunkLRU.splice(vi, 1)[0];
        (chunkOwned[cid] || []).forEach(function (n) { delete presets[n]; });
        delete chunkOwned[cid];
        delete chunkState[cid]; // unloaded again; a later access re-injects
        const s = chunkScripts[cid];
        if (s && s.parentNode) s.parentNode.removeChild(s);
        delete chunkScripts[cid];
      }
    }

    global.__bcPresetChunk = function (cid, chunkPresets) {
      if (chunkState[cid] === 'loaded') return;
      const owned = [];
      Object.keys(chunkPresets).forEach(function (k) {
        // Only fill names this chunk is the registered source for, so a
        // chunk can never override vendored presets or other chunks.
        if (extraChunkOf[k] === cid) { presets[k] = chunkPresets[k]; owned.push(k); }
      });
      chunkOwned[cid] = owned;
      chunkState[cid] = 'loaded';
      touchChunk(cid);
      evictChunks();
      settleChunk(cid, true);
    };

    // Resolves true once the chunk's presets are resident, false if the
    // chunk can't be loaded (never rejects). Concurrent calls share one load.
    function ensureChunk(cid) {
      if (chunkState[cid] === 'loaded') {
        touchChunk(cid);
        return Promise.resolve(true);
      }
      if (chunkState[cid] === 'failed') return Promise.resolve(false);
      return new Promise(function (resolve) {
        (chunkWaiters[cid] = chunkWaiters[cid] || []).push(resolve);
        if (chunkState[cid] === 'loading') return;
        chunkState[cid] = 'loading';

        function fail() {
          if (chunkState[cid] !== 'loading') return;
          chunkState[cid] = 'failed';
          // Poison every name served by this chunk so rotation skips them
          // instead of retrying a broken/missing file forever.
          (extraIndex.chunks[cid] || []).forEach(function (n) {
            if (extraChunkOf[n] === cid) failed.add(n);
          });
          settleChunk(cid, false);
        }

        const timer = setTimeout(fail, 10000);
        const s = document.createElement('script');
        s.src = 'presets-extra/chunk-' + String(cid).padStart(3, '0') + '.js';
        s.onerror = function () { clearTimeout(timer); fail(); };
        s.onload = function () { clearTimeout(timer); fail(); }; // no-op if the chunk registered
        chunkScripts[cid] = s;
        document.head.appendChild(s);
      });
    }

    function sizeCanvas() {
      const dpr = global.devicePixelRatio || 1;
      canvas.width  = global.innerWidth  * dpr;
      canvas.height = global.innerHeight * dpr;
      if (visualizer) visualizer.setRendererSize(canvas.width, canvas.height);
    }

    // Guards async chunk loads: only the most recent request may apply its
    // preset, so rapid next/random presses can't finish out of order.
    let loadSeq = 0;

    function loadPreset(i, blend, announce) {
      if (!visualizer || !keys.length) return;
      i = (i + keys.length) % keys.length;
      const seq = ++loadSeq;

      // Walk forward over resident presets, skipping any butterchurn rejects.
      // This is a bounded loop rather than recursion: the big collection is
      // uncurated, so a run of broken presets (or, pathologically, an
      // all-broken library where stepIndex can only return failed entries)
      // must not grow the stack or spin forever.
      for (let attempts = 0; attempts < keys.length; attempts++) {
        const name = keys[i];

        if (!(name in presets)) {
          // Extra preset whose chunk isn't resident yet: load it, then re-enter.
          // Advance the logical cursor now, before the async load: otherwise idx
          // stays on the old preset until the chunk callback, and a rapid second
          // request (mashing X/next, or the cycle timer) re-reads the same idx and
          // supersedes this callback via the seq guard — stranding playback. The
          // seq guard still governs the actual visualizer.loadPreset application.
          const at = i;
          idx = at;
          ensureChunk(extraChunkOf[name]).then(function (ok) {
            if (seq !== loadSeq) return; // superseded by a newer request
            if (!ok || !(name in presets)) {
              onToast('\u26A0 preset unavailable, skipping: ' + name);
              idx = at;
              if (failed.size + excluded.size < keys.length) loadPreset(stepIndex(1), blend, announce);
              return;
            }
            loadPreset(at, blend, announce);
          });
          return;
        }

        idx = i;
        const cid = extraChunkOf[name];
        if (cid != null) touchChunk(cid);
        try {
          visualizer.loadPreset(presets[name], blend != null ? blend : defaultBlend);
        } catch (e) {
          failed.add(name);
          onToast('\u26A0 broken preset skipped: ' + name);
          i = stepIndex(1);
          continue;
        }
        onPreset(idx, keys[idx]);
        if (announce !== false) onToast(keys[idx]);
        return;
      }

      // Exhausted every preset without one that renders.
      onToast('\u26A0 no working preset found');
    }

    // Steps from idx in the given direction, skipping excluded and failed
    // presets. Falls back to a plain step if every other preset is skipped,
    // so playback never gets stuck.
    function stepIndex(dir) {
      if (!keys.length) return idx;
      let i = idx;
      for (let n = 0; n < keys.length; n++) {
        i = (i + dir + keys.length) % keys.length;
        if (!excluded.has(keys[i]) && !failed.has(keys[i])) return i;
      }
      return (idx + dir + keys.length) % keys.length;
    }

    // Indices eligible for a random pick: everything but the current preset
    // and anything excluded or failed. Falls back to "everything but current"
    // if that would otherwise be empty.
    function candidatePool() {
      let pool = keys.map(function (_, i) { return i; })
        .filter(function (i) {
          return i !== idx && !excluded.has(keys[i]) && !failed.has(keys[i]);
        });
      if (!pool.length) {
        pool = keys.map(function (_, i) { return i; }).filter(function (i) { return i !== idx; });
      }
      return pool;
    }

    function loadRandom() {
      if (keys.length < 2) return loadPreset(0);
      const pool = candidatePool();
      loadPreset(pool[Math.floor(Math.random() * pool.length)]);
    }

    function restartCycle() {
      if (cycleTimer) clearInterval(cycleTimer);
      if (cycleOn) cycleTimer = setInterval(function () {
        if (shuffleOn) loadRandom(); else loadPreset(stepIndex(1));
      }, cycleSecs * 1000);
    }

    // Excludes the currently playing preset from shuffle/cycle rotation for
    // the rest of this session (in-memory only) and advances off it.
    function removeCurrentFromShuffle() {
      if (!keys.length) return null;
      const removed = keys[idx];
      excluded.add(removed);
      // Advance off the removed preset the same way the cycle does: a random
      // pick when shuffling, otherwise the next in sequence. candidatePool()
      // already skips excluded/failed, so the just-removed preset is avoided.
      if (shuffleOn) loadRandom(); else loadPreset(stepIndex(1));
      restartCycle();  // give the newly chosen preset its full interval
      return removed;
    }

    async function getDevices() {
      try {
        const all = await navigator.mediaDevices.enumerateDevices();
        inputDevices = all.filter(function (d) { return d.kind === 'audioinput'; });
      } catch (e) {
        inputDevices = [];
      }
      return inputDevices;
    }

    function connectStream(stream) {
      if (micStream && micStream !== stream) {
        micStream.getTracks().forEach(function (t) { t.stop(); });
      }
      if (sourceNode) visualizer.disconnectAudio(sourceNode);
      micStream = stream;
      sourceNode = audioCtx.createMediaStreamSource(stream);
      visualizer.connectAudio(sourceNode);
    }

    async function openStream(deviceId) {
      const audio = { echoCancellation: false, noiseSuppression: false, autoGainControl: false };
      if (deviceId) audio.deviceId = { exact: deviceId };
      return navigator.mediaDevices.getUserMedia({ audio: audio });
    }

    async function useDevice(i) {
      if (!inputDevices.length) await getDevices();
      if (!inputDevices.length) return null;
      deviceIdx = (i + inputDevices.length) % inputDevices.length;
      const dev = inputDevices[deviceIdx];
      connectStream(await openStream(dev.deviceId));
      onToast('\uD83C\uDF99 ' + (dev.label || ('Input ' + (deviceIdx + 1))));
      return dev;
    }

    async function useDeviceById(id) {
      if (!inputDevices.length) await getDevices();
      const i = inputDevices.findIndex(function (d) { return d.deviceId === id; });
      if (i >= 0) return useDevice(i);
      return null;
    }

    async function start(deviceId) {
      if (started || starting) return;
      if (!Butterchurn) {
        onToast('\u26A0 butterchurn failed to load');
        throw new Error('butterchurn library not loaded');
      }
      starting = true;
      try {
        audioCtx = new (global.AudioContext || global.webkitAudioContext)();
        await audioCtx.resume();

        const stream = await openStream(deviceId);   // also triggers the permission prompt
        await getDevices();                           // labels populate after permission

        visualizer = Butterchurn.createVisualizer(audioCtx, canvas, {
          width: canvas.width, height: canvas.height, pixelRatio: 1, textureRatio: 1
        });
        const ImagesLib = getLib('butterchurnExtraImages');
        if (ImagesLib && ImagesLib.getImages) {
          // Custom textures used by a handful of presets; optional — presets
          // render without them, just with plainer backgrounds.
          try { visualizer.loadExtraImages(ImagesLib.getImages()); } catch (e) {
            console.warn('Failed to load extra images (non-critical):', e);
          }
        }
        connectStream(stream);
        started = true;
      } catch (e) {
        // Don't leak an AudioContext per failed attempt \u2014 browsers cap them.
        if (audioCtx) { audioCtx.close(); audioCtx = null; }
        throw e;
      } finally {
        starting = false;
      }

      // First paint should never wait on a chunk fetch: start on an
      // already-resident (vendored) preset. Normally the first one, for a
      // stable default; with randomFirst set, a random resident preset so
      // each launch opens on something different (still no chunk fetch).
      const resident = [];
      for (let k = 0; k < keys.length; k++) {
        if (keys[k] in presets) resident.push(k);
      }
      let first = resident.length ? resident[0] : 0;
      if (opts.randomFirst && resident.length) {
        first = resident[Math.floor(Math.random() * resident.length)];
      }
      loadPreset(first, 0, false);
      (function render() { visualizer.render(); requestAnimationFrame(render); })();
      restartCycle();
    }

    global.addEventListener('resize', sizeCanvas);
    sizeCanvas();

    return {
      start:         start,
      // Manual navigation resets the auto-cycle countdown (restartCycle is a
      // no-op when cycling is off) so a chosen preset gets its full interval.
      next:          function () { loadPreset(stepIndex(1)); restartCycle(); },
      prev:          function () { loadPreset(stepIndex(-1)); restartCycle(); },
      random:        function () { loadRandom(); restartCycle(); },
      goto:          function (i, announce) { loadPreset(i, undefined, announce); restartCycle(); },
      toggleCycle:   function () { cycleOn = !cycleOn; restartCycle(); return cycleOn; },
      toggleShuffle: function () { shuffleOn = !shuffleOn; return shuffleOn; },
      isShuffling:   function () { return shuffleOn; },
      removeCurrentFromShuffle: removeCurrentFromShuffle,
      excludedList:  function () { return Array.from(excluded); },
      setCycleSecs:  function (s) {
        cycleSecs = Math.max(3, s | 0); restartCycle(); return cycleSecs;
      },
      getCycleSecs:  function () { return cycleSecs; },
      isCycling:     function () { return cycleOn; },
      nextDevice:    function () { return useDevice(deviceIdx + 1); },
      useDevice:     useDevice,
      useDeviceById: useDeviceById,
      getDevices:    getDevices,
      listDevices:   function () { return inputDevices.slice(); },
      keys:          function () { return keys.slice(); },
      currentIndex:  function () { return idx; },
      currentName:   function () { return keys[idx] || ''; },
      isStarted:     function () { return started; },
      resize:        sizeCanvas
    };
  }

  global.BCViz = { create: create };
})(window);
